### PR TITLE
Resume suspended VMs without explicit `--suspendable` flag

### PR DESCRIPTION
**Pull request by fkorotkov**

### CODE REVIEW

**Review by edigaryev — APPROVED** [review]

**Comment by Jon889** [comment]
@fkorotkov is there a way to have a VM run ephemerally in that it will restore from the saved state but not save the state at the end. Then the next time the VM runs it will restore from the same/original saved state

**Comment by fkorotkov** [comment]
@Jon889 you can clone a VM into a temporary one which is very fast and will clone the state. Then you can run this temporary VM and delete it once not needed anymore.

**Comment by Jon889** [comment]
Ah I thought that would invalidate the snapshot, as then multiple machines could be run. Also is it not possible to use snapshots with mounted directories? I get `Failed to suspend the VM: Invalid virtual machine configuration. Unsupported directory sharing device in configuration.` in which case it seems like tart shouldn't allow --suspendable and --dir to be used together

**Comment by fkorotkov** [comment]
Sees you can resume a suspended VM with a mounted directory though. So you can run a suspendable VM without a mount, configure it and suspend. Then resume it again but this time with a mounted directory. The only part that is failing is the actual suspending of a VM with a mounted directory.

**Comment by Jon889** [comment]
@fkorotkov Do you think there is any way around not being able to use suspendible VMs with mounted directories? macOS should have the ability to do it as USB drives can be plugged in and out without any notice.

**Comment by edigaryev** [comment]
> @fkorotkov Do you think there is any way around not being able to use suspendible VMs with mounted directories? macOS should have the ability to do it as USB drives can be plugged in and out without any notice.

Unfortunately `Virtualization.Framework` does not support mounting USB drives yet, see https://github.com/cirruslabs/tart/issues/139 and https://github.com/utmapp/UTM/issues/3778 for more details.

[Mounting a block device](https://github.com/cirruslabs/tart/pull/611) could be an option, but a quick test shows that it also works incorrectly because the guest seems to be overwriting the host's device state/file table on resume from snapshot.

**Pull request merged**
