### PR TITLE
Downloads disk layers in parallel

### LINKED ISSUE #279: Poor performance pulling and pushing to ECR
Hi!

I'm not getting great performance with ECR. That is an issue for us because we are integrating tart into our macOS CI, which looks like this: pull an image, do things to it, and push the result back. As it stands, tart adds quite a lot of latency before tests can run, due to the slow pulling speed. Pushing is also an issue that prevents the jobs from moving on after the builds are finished.

I recently updated to release 0.30.0 hoping to improve this, so the numbers below are on this release.

I'm getting around 14MB/s when uploading, the image below is 27GB compressed and uploaded in 33min
```
> tart push tag ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/macos/repo:tag
21:13:11.446744Z   pushing tag to ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/macos/repo:tag...
21:13:11.479768Z   pushing config...
21:13:12.239447Z   pushing disk... this will take a while...
21:13:12.240589Z   0%

...

21:36:53.809777Z   100%
21:37:01.597372Z   pushing NVRAM...
21:37:03.378103Z   pushing manifest for tag...
```

Here is an example of pulling a 37.7GB image that took 1h20, so pulling is slower at 8MB/s.
```
> tart pull ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/macos/repo:tag
15:20:29.398440Z   pulling ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/macos/repo:tag...
15:20:29.398715Z   pulling manifest...
15:20:30.011137Z   pulling disk (37.7 GB compressed)...
15:20:30.011326Z   0%

...

16:42:32.350457Z   100%
16:42:32.381668Z   pulling NVRAM...
```

My setup is an AWS mac2.metal (M1 mac mini), hosted in the eu-west-1 region and working with ECR in that same region. The disk is a 500GB EBS gp2 volume which should provide 250 MB/s of throughput, and the network is a 10Gb/s link. 

I would appreciate any help to improve the performance. I'm also working with @saracen, who you've already been in touch with.

### PR DESCRIPTION
**Pull request by fkorotkov**
This change makes the `pull` to download layers in parallel into separate files. Than all the files are sequentially decompressed and are written into the resulting `disk.img`.

This change allowed to fully saturate a 1 Gbps connection while consuming around 30 Mb of RAM.

Fixes #279 #234 #283

### CODE REVIEW

**Comment by fkorotkov** [comment]
@adrienkohlbecker will be interesting to see if you can check this binary https://api.cirrus-ci.com/v1/artifact/task/5985352270741504/binary/.build/debug/tart in your AWS setup.

**Comment by fkorotkov** [comment]
On the second thought I think I'll try to follow up with a change to download layers in parallel into temporary files and then I archive them into the final disk file.

**Comment by fkorotkov** [comment]
@adrienkohlbecker  we went with less invasive refactoring in #282 which showed the same results in our test environment with 1 Gbps connection. I winder if you can run some experiment in your 10 Gbps case. Could you please try a [binary from this PR](https://api.cirrus-ci.com/v1/artifact/task/5287316603273216/binary/.build/debug/tart) vs `0.32.0` version.

**Comment by edigaryev** [comment]
This change gets the job done indeed, but is way too intrusive, as you've noted above.

What do you think about a version of this that would abstract all of the `URLSession.download()` details and file-related peculiarities away, essentially providing a `URLSession.bytes()` replacement, but faster (probably using a different return type for it's first argument, similarly to what's been done in https://github.com/cirruslabs/tart/pull/282).

Not only this will simplify the changeset and it's reviewal, but allow for easier "URL fetcher" mechanism swaps in the future, similarly to what's been already done with `Network` protocol.

**Comment by fkorotkov** [comment]
Abstracted all the work with `URLSession` into static methods of a new class called `URLFetcher`.

Since #282 fixed the regression. Please look at this change as a further improvement and not a replacement for. This optimization of downloading in parallel to files on disk is a common pattern. This optimization IMO should show the best possible performance in terms of memory consumption and IO utilization.

**Comment by edigaryev** [comment]
I've gave this one more shot today and still think this can be implemented way more cleanly by properly abstracting the `URLSession.shared.data()` and `URLSession.shared.download()` methods, as I've mentioned above.

In `VMDirectory+OCI.swift`, it seems that the code is actually re-reading the downloaded blobs into memory. What if we expose two methods in `Fetcher`:

* `fetch() -> (AsyncThrowingChannel<Data, Error>, HTTPURLResponse)`
  * calls `URLSession.shared.data()`
  * streams the received contents to the channel (once)
* `fetchViaFile() -> (AsyncThrowingChannel<Data, Error>, HTTPURLResponse)`
  * calls `URLSession.shared.download()`
  * opens `FileHandle` to the downloaded file
  * removes downloaded file
  * streams `FileHandle`'s contents to the channel (multiple times)

Then, in `Registry.authAwareRequest()`, introduce an argument `viaFile: Bool = false`, which will work like this:

```swift
if viaFile {
  return try await Fetcher().fetchViaFile(request)
}

return try await Fetcher().fetch(request)
```

Then, set `viaFile: true` in `Registry.pullBlob()` to only download blobs using files.

This abstraction would dramatically reduce the code changes needed to support parallel blob downloads via files, prevent repeatable authentication logic in `Registry` and allow us to more quickly switch to other method in the future, because we won't be tied to dealing with files.

**Pull request closed without merging**
