### PR TITLE
VMStorageOCI: percent-encode the colon in RemoteName's host

### PR DESCRIPTION
**Pull request by edigaryev**
Resolves https://github.com/cirruslabs/tart/issues/827.

### CODE REVIEW

**Comment by fkorotkov** [comment]
Should we just ignore port for storing OCI images? Don't think anyone will ever have two registries on different ports. 🤔

**Comment by edigaryev** [comment]
> Should we just ignore port for storing OCI images? Don't think anyone will ever have two registries on different ports. 🤔

IMO we should not assume anything about things that are security-related. It's hard to say exactly what registry configurations people could be using.

**Comment by fkorotkov** [comment]
I just don't like String extensions that are used at specific location. This is an edge case for hosts and preferably this logic should be isolated. For example, I'll need time to understand why [this line](https://github.com/cirruslabs/tart/pull/828/files#diff-52d106b7150fe2a5d777ea88144bbf0a07f23d521a973fa1fd92133ab223fec3R116) is changed and think if we covered all the places. There is a feeling this host specific logic should be better scoped.

**Comment by edigaryev** [comment]
> I just don't like String extensions that are used at specific location.

Switched to an ordinary funcions in https://github.com/cirruslabs/tart/pull/828/commits/09196066274040add041fdaeaa8cf60cbf081294 and added a comment explaining this: https://github.com/cirruslabs/tart/blob/7c386e3466aaa4afe22732b74434a464555d6135/Sources/tart/VMStorageOCI.swift#L116

**Review by fkorotkov — APPROVED** [review]

**Pull request merged**
