### PR TITLE
tart run: introduce --disk option

### PR DESCRIPTION
**Pull request by edigaryev**
Resolves https://github.com/cirruslabs/tart/issues/150.

### CODE REVIEW

**Comment by fkorotkov** [comment]
I wonder if if we need to add documentation on how to create a disk like that. 🤔

**Comment by edigaryev** [comment]
> I wonder if if we need to add documentation on how to create a disk like that. 🤔

The most straightforward way seems to be using the Disk Utility and following the [Create a disk image using Disk Utility on Mac](https://support.apple.com/en-gb/guide/disk-utility/dskutl11888/mac) guide.

Should we include it in the `tart run --help` or add to the `README.md`?

**Comment by fkorotkov** [comment]
Let's maybe add the link to the `disscussion`. Something like "Learn how to create a disk image using Disk Utility here https://support.apple.com/en-gb/guide/disk-utility/dskutl11888/mac". 🤔

**Comment by edigaryev** [comment]
> Let's maybe add the link to the `disscussion`. Something like "Learn how to create a disk image using Disk Utility here https://support.apple.com/en-gb/guide/disk-utility/dskutl11888/mac". 🤔

Added in https://github.com/cirruslabs/tart/pull/156/commits/d5dc9e0f9864ae11a565c55634fea2d7b76e24da.

**Review by fkorotkov — APPROVED** [review]

**Pull request merged**
