### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by fkorotkov**

### CODE REVIEW

**Comment by sogajeffrey** [comment]
@edigaryev @fkorotkov why was AGPL selected as the License? many companies cannot use tools with AGPL license. Any chance it can be changed to something like Apache or MIT?

**Comment by fkorotkov** [comment]
Hey @sogajeffrey, coincidently someone asked the same question yesterday and I tried to explain our reasoning here https://github.com/cirruslabs/tart/discussions/369. Feel free to comment there or email me directly at fedor@cirruslabs.org.

**Comment by oleg-z** [comment]
@fkorotkov no coincidence here. We're on the same team =)

**Comment by fkorotkov** [comment]
😅 got it! I suspected that. Might be a good idea to have a quick call next week or after NYE to talk about your concerns and how can we help but at the same time be protected from AWS-like takeovers.

**Pull request merged**
