### PR TITLE
Suspend/resume support

### PR DESCRIPTION
**Pull request by edigaryev**
Unfortunately, changing the MAC-address after the snapshot is created is not possible (`Virtualization.Framework` throws an invalid argument exception when restoring), so we're not preserving the VM state when `tart clone`'ing.

Resolves https://github.com/cirruslabs/tart/issues/147.

### CODE REVIEW

**Review by fkorotkov — COMMENTED** [review]
What happens when an audio and entropy devices are attached? Is it crashing. IMO it should work with them. Weird that it's not working and maybe newer versions of Sonoma will fix it.

Also what do you think of making VM to suspend on the current `Cmd + C` or closing the window?

**Comment by edigaryev** [comment]
> Is it crashing.

Yes, see https://github.com/cirruslabs/tart/issues/147#issuecomment-1580969378.

**Comment by edigaryev** [comment]
> Also what do you think of making VM to suspend on the current `Cmd + C` or closing the window?

How would the user shutdown the VM without taking a snapshot then?

Doing a clean "Shut Down" from inside of a VM is slower than simply closing the window and might not always be an option when the VM is unresponsive.

**Comment by edigaryev** [comment]
Enabled automatic suspending of the VM when closing Tart's window and using `--suspendable`.

We can think of better ways of detecting whether we need to suspend or stop the VM later, when `--suspendable` is not needed anymore.

**Review by fkorotkov — APPROVED** [review]

**Pull request merged**
