### PR TITLE
Set up automatic installation of shell completion files

### PR DESCRIPTION
**Pull request by bartekpacia**
Same as https://github.com/cirruslabs/orchard/pull/157 and https://github.com/cirruslabs/cirrus-cli/pull/696

Learn more: https://apple.github.io/swift-argument-parser/documentation/argumentparser/installingcompletionscripts

### CODE REVIEW

**Review by fkorotkov — APPROVED** [review]

**Review by edigaryev — APPROVED** [review]

**Comment by torarnv** [comment]
```
❯ brew upgrade tart
==> Upgrading 1 outdated package:
cirruslabs/cli/tart 2.7.2 -> 2.8.0
==> Fetching cirruslabs/cli/tart
==> Downloading https://github.com/cirruslabs/tart/releases/download/2.8.0/tart-arm64.tar.gz
Already downloaded: /Users/torarne/Library/Caches/Homebrew/downloads/8797b6e03f2f615f811d53fb0dfe6b60768488707feba2f3a8c5bba1a026d428--tart-arm64.tar.gz
==> Upgrading cirruslabs/cli/tart
  2.7.2 -> 2.8.0
brew: exec failed: {"SHELL"=>"bash"}
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/tart/2.8.0/bin/tart --generate-completion-script bash` exited with 1. Here's the output:
```

**Comment by torarnv** [comment]
```
❯ brew upgrade tart --verbose
==> Upgrading 1 outdated package:
cirruslabs/cli/tart 2.7.2 -> 2.8.0
==> Fetching cirruslabs/cli/tart
==> Downloading https://github.com/cirruslabs/tart/releases/download/2.8.0/tart-arm64.tar.gz
Already downloaded: /Users/torarne/Library/Caches/Homebrew/downloads/8797b6e03f2f615f811d53fb0dfe6b60768488707feba2f3a8c5bba1a026d428--tart-arm64.tar.gz
==> Verifying checksum for '8797b6e03f2f615f811d53fb0dfe6b60768488707feba2f3a8c5bba1a026d428--tart-arm64.tar.gz'
==> Upgrading cirruslabs/cli/tart
  2.7.2 -> 2.8.0
rm /opt/homebrew/bin/tart
/usr/bin/env tar --extract --no-same-owner --file /Users/torarne/Library/Caches/Homebrew/downloads/8797b6e03f2f615f811d53fb0dfe6b60768488707feba2f3a8c5bba1a026d428--tart-arm64.tar.gz --directory /private/tmp/homebrew-unpack20240403-29373-hctg4a
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240403-29373-hctg4a/LICENSE /private/tmp/tart-20240403-29373-nx3rq4/LICENSE
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240403-29373-hctg4a/tart.app/. /private/tmp/tart-20240403-29373-nx3rq4/tart.app
brew: exec failed: {"SHELL"=>"bash"}
ln -s ../Cellar/tart/2.7.2/bin/tart tart
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/tart/2.8.0/bin/tart --generate-completion-script bash` exited with 1. Here's the output:
```

**Comment by torarnv** [comment]
Not sure why it's trying to do `ln -s ../Cellar/tart/2.7.2/bin/tart tart`

**Comment by torarnv** [comment]
https://github.com/torarnv/tart/pull/new/generate-completions-using-tart-app

**Pull request merged**
