### PR TITLE
Support chunked uploads

### PR DESCRIPTION
**Pull request by fkorotkov**
As described in https://docs.docker.com/registry/spec/api/#pushing-a-layer

Should help with #158

### CODE REVIEW

**Comment by fkorotkov** [comment]
I've tested by uploading an image to ECR. Before the change it was barely doing anything, with the change I see 30-40 MB/s uploads. Will verify with GitHub Packages shortly too...

**Comment by fkorotkov** [comment]
Just tried to push the latest Ventura beta to ghcr.io using the branch. Had to lower the chunk size and also fixed range end index (it's inclusive). See [6e3df64](https://github.com/cirruslabs/tart/pull/159/commits/6e3df64a7c98c9e618fa4727ee20caf85e2cb471)

**Comment by fkorotkov** [comment]
But now ECR is not working with a 500 with no message. Seems the empty `PUT` is not working as expected. Will refactor to do the last put for the last chunk.

**Comment by fkorotkov** [comment]
It appeared that not all registries support chunked uploads so I introduced a new `--chunk-size` option. 

`tart push --chunk-size=10` should fix #158 for @victor-yousician

**Comment by fkorotkov** [comment]
Closing in favor of #168

**Comment by fkorotkov** [comment]
Reopened for further discussion of this change being a feature rather then a bug fix.

**Review by edigaryev — APPROVED** [review]

**Pull request merged**
